variables:
- group: ${{ variables['Build.SourceBranchName'] }}
- name: templateFile
  value: ciam.bicep

trigger:
  branches:
    include:
    - dev
    - qa
    - prd
  paths:
    include:
    - ciam.bicep
    - ciam-app-config.json
    - ciam-pipeline.yml
    - emailtemplates
    - email-header.html
    - email-footer.html
    - replacements

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    az bicep build --file $(templateFile)
  name: LintBicepCode
  displayName: Run Bicep Linter

- task: AzureCLI@2
  name: RunPreflightValidation
  displayName: Run Preflight Validation
  inputs:
    azureSubscription: $(ciamServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group validate --resource-group $(ciamResourceGroupName) \
        -f $(templateFile) --parameters cdcApiKey=$(cdcApiKey) cdcDC=$(cdcDC) cdcAppKey=$(cdcAppKey) cdcAppSecret=$(cdcAppSecret)

- task: AzureCLI@2
  name: Deploy
  displayName: Deploy to Azure
  inputs:
    azureSubscription: $(ciamServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      sed -i -e "$(jq -nrc --slurpfile r replacements '$r | map(select(.e=="'$(Build.SourceBranchName)'") | "s/{{"+.n+"}}/"+.r+"/g") | join(";")')" $(templateFile)
      az deployment group create --name $(Build.BuildNumber)  --resource-group $(ciamResourceGroupName) \
        -f $(templateFile) --parameters cdcApiKey=$(cdcApiKey) cdcDC=$(cdcDC) cdcAppKey=$(cdcAppKey) cdcAppSecret=$(cdcAppSecret)

- task: AzureCLI@2
  name: WriteAppConfig
  displayName: Write App Config
  inputs:
    azureSubscription: $(ciamServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      sed -i -e "$(jq -nrc --slurpfile r replacements '$r | map(select(.e=="'$(Build.SourceBranchName)'") | "s/{{"+.n+"}}/"+.r+"/g") | join(";")')" ciam-app-config.json
      az appconfig kv import -y -n $(echo $(ciamResourceGroupName) | sed 's/RG/CS/; s/[^-]*$/AppConfig/') -s file --format json \
        --path ciam-app-config.json --profile appconfig/kvset

- task: AzureCLI@2
  name: UploadEmailTemplates
  displayName: Upload Email Templates
  inputs:
    azureSubscription: $(ciamServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      mkdir -p emailtemplates
      find ./emailtemplates -type f -exec perl -i -0777pe '$h=`cat email-header.html`; $f=`cat email-footer.html`; s/(?<=<!-- BEGIN HEADER -->)(.|\n)+?(?=<!-- END HEADER -->)/$h/; s/(?<=<!-- BEGIN FOOTER -->)(.|\n)+?(?=<!-- END FOOTER -->)/$f/;s/{{current-year}}/'$(date +%Y)'/g;'"$(jq -nrc --slurpfile r replacements '$r | map(select(.e=="$(Build.SourceBranchName)") | "s/{{"+.n+"}}/"+.r+"/g") | join(";")')" {} \;
      az storage blob upload-batch --account-name $(echo $(ciamResourceGroupName) | sed 's/RG/st/; s/[^-]*$/storage/; s/-/1/g; s/.*/\L&/') \
        -d emailtemplates -s ./emailtemplates --overwrite

