variables:
- group: ${{ variables['Build.SourceBranchName'] }}
- name: templateFile
  value: shared.bicep

trigger:
  branches:
    include:
    - dev
    - qa
    - prd 
  paths:
    include:
    - shared.bicep
    - shared-pipeline.yml

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    az bicep build --file $(templateFile)
  name: LintBicepCode
  displayName: Run Bicep Linter

- task: AzureCLI@2
  name: RunPreflightValidation
  displayName: Run Preflight Validation
  inputs:
    azureSubscription: $(sharedServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group validate --resource-group $(sharedResourceGroupName) \
        -f $(templateFile) --parameters cdcApiKey=$(cdcApiKey) cdcDC=$(cdcDC) cdcAppKey=$(cdcAppKey) cdcAppSecret=$(cdcAppSecret) marketingSubscriptionId=$(marketingSubscriptionId)
        
- task: AzureCLI@2
  name: Deploy
  displayName: Deploy to Azure
  inputs:
    azureSubscription: $(sharedServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --name $(Build.BuildNumber)  --resource-group $(sharedResourceGroupName) \
        -f $(templateFile) --parameters cdcApiKey=$(cdcApiKey) cdcDC=$(cdcDC) cdcAppKey=$(cdcAppKey) cdcAppSecret=$(cdcAppSecret) marketingSubscriptionId=$(marketingSubscriptionId)
