@businessUnitId = 4_3d1ENwGnb3asfrtNekTJWg

###

# @name groups
GET https://cdp.eu5.gigya.com/api/businessunits/{{businessUnitId}}/schemas/HEf3OzVo__Sa7i4Ef8cszg/groups
    ?userKey={{cdc-user-key}}
    &secret={{cdc-user-secret}}
Content-Type: application/x-www-form-urlencoded

query=SELECT * FROM groups

###

# @name customerschemas
GET https://cdp.eu5.gigya.com/api/businessunits/{{businessUnitId}}/customerschemas
    ?userKey={{cdc-user-key}}
    &secret={{cdc-user-secret}}
Content-Type: application/x-www-form-urlencoded

